#!/bin/sh

GOROOT=/usr/local/go; export GOROOT
GO15VENDOREXPERIMENT=1; export GO15VENDOREXPERIMENT

if [ -z "`echo $PATH | grep -o "$GOROOT"`" ]; then
	PATH=$PATH:$GOROOT/bin; export PATH
fi

if [ -z "$GOPATH" ]; then
	GOPATH=`pwd`; export GOPATH
fi

if [ -z "`echo $PATH | grep -o "$GOPATH/bin"`" ]; then
	PATH=$PATH:$GOPATH/bin; export PATH
fi

if [ -z "`echo $PS1 | grep -o "GOPATH=$GOPATH"`" ]; then
	PS1="GOPATH=$GOPATH\n$PS1"; export PS1
fi

