#!/bin/sh

GOROOT=/usr/local/go; export GOROOT
if [ -z "`echo $PATH | grep -o "$GOROOT"`" ]; then
	PATH=$PATH:$GOROOT/bin; export PATH
fi

if [ -z "$GOPATH" ]; then
	GOPATH=`pwd`; export GOPATH
fi

if [ -z "`echo $PATH | grep -o "$GOPATH/bin"`" ]; then
	PATH=$PATH:$GOPATH/bin; export PATH
fi
